# Generated by Django 3.0.5 on 2021-10-17 03:56

import django.core.validators
from django.db import migrations, models
import fileUpload.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpload', '0002_auto_20211016_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='upload',
            field=models.FileField(upload_to=fileUpload.models.dir_path_name, validators=[django.core.validators.FileExtensionValidator(['mat', 'csv'])]),
        ),
    ]
