# Generated by Django 3.0.5 on 2021-10-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FourierTransform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sf', models.PositiveIntegerField(default=500)),
                ('is_excluded', models.BooleanField(default=True, verbose_name='exclude_10s')),
                ('line_is_specified', models.BooleanField(default=False, verbose_name='line_is_specified')),
                ('spec_line', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
