# Generated by Django 3.0.5 on 2021-10-21 04:41

import django.core.validators
from django.db import migrations, models
import fourierTransform.models


class Migration(migrations.Migration):

    dependencies = [
        ('fourierTransform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=fourierTransform.models.dir_path_name, validators=[django.core.validators.FileExtensionValidator(['mat', 'csv'])])),
            ],
        ),
    ]
